name: CI

on:
    push:
        branches:
            - "main"
    pull_request:
            branches:
            - "main"

    workflow_dispatch:


jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                python-version: [3.12]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Create and active virtualenv
              run: |
                  python -m venv .venv
                  echo "source .venv/bin/activate" >> $GITHUB_PATH
            - name: Install project
              run: |
                run: |
                  source .venv/bin/activate
                  pip install -e '.[test]'
            - name: Run tests
              run: |
                . .venv/bin/activate
                pytest -v --junitxml=$(PWD)/test-result.xml
            - name: publish junit results
              uses: EnricoMi/publish-unit-test-result-action@v1.40
              if: always()
              with:
                files: "test-result.xml"
                check_name: "Test Result (Python ${{matrix.python-version}})"
                github_token: ${{ secrets.GITHUB_TOKEN }}

